theme: jekyll
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Stochastic Modeling and Processes
permalink: /SMP1
description: This is a site for the course Stochastic Modeling and Processes
markdown: kramdown
kramdown:
  parse_block_html: true