theme: jekyll
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Stochastic Modeling and Processes
description: This is a site for the course Stochastic Modeling and Processes. Click <a href='/SMP1'>here</a> to return to the main page
markdown: kramdown
kramdown:
  parse_block_html: true